import "./globals.css";
import Topo from './componentes/Topo/Topo';
import Rodape from './componentes/Rodape/Rodape'


export const metadata = {
  title: "Sorveteria Artesanal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body >
        <Topo />
        {children}
        <Rodape />
      </body>
    </html>
  );
}
